cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),

]

shop/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^city/(?P<slug>[-\w]+)/$', views.ProductCityList.as_view(), name='city'),
    # url(r'^category/(?P<slug>[-\w]+)/$', views.ProductCityList.as_view()),
    # url(r'^$', views.ProductCityList.as_view()),
    # url(r'^$', views.ProductList, name='ProductList'),
    # url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),

]




# url(r'^$', views.ProductCityList.as_view()),
# url(r'^city/(?P<city_slug>[-\w]+)/$', views.ProductCityList.as_view()),
# url(r'^(?P<slug>[-\w]+)/$', views.ProductCityList.as_view(), name='citylist'),
# url(r'^(?P<slug>[-\w]+)/$', views.ProductCityList.as_view(), name='categorylist'),
# url(r'^city1/(?P<slug>[-\w]+)/$', views.CityListView.as_view(), name='City'),
# url(r'^city1/(?P<slug>[-\w]+)/$', views.CityListView.as_view(), name='Category'),
# url(r'^city1/page(?P<page>\d+)/$', views.CityListView.as_view()),

svadba/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
# Модель города
class City(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Город')
    slug = models.SlugField(max_length=150, verbose_name='Транслит', null=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:citylist', args=[self.slug])

# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория")
    city = models.ForeignKey(City, related_name='products', verbose_name="Город")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    tel = models.CharField(max_length=16, verbose_name='Тел.номер')
    # stock = models.PositiveIntegerField(verbose_name="На складе")
    # available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, City
from cart.forms import CartAddProductForm
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.



#
# class VProducts(ListView):
#     template_name = 'shop/index.html'
#     context_object_name = 'vproducts'
#     model = Product
#     def get_queryset(self):
#         qs = Product.objects.all()
#         return qs
#
class ProductCityList(ListView):
    template_name = 'shop/category/city.html'
    context_object_name = 'products'
    model = Product
    def get_queryset(self):
        city_filter = self.request.GET.get('city', '')
        cat_filter = self.request.GET.get('category', '').split(',')
        if not isinstance(cat_filter, (list, tuple)):
            cat_filter = list(cat_filter)
        products = Product.objects.all()
        if city_filter:
            products = products.filter(city=city_filter)
        if cat_filter:
            products = products.filter(category__slug__in=cat_filter)
        return products

# # Страница с товарами
# def ProductList(request, category_slug=None):
#     category = None
#     categories = Category.objects.all()
#     products = Product.objects.all()
#     if category_slug:
#         category = get_object_or_404(Category, slug=category_slug)
#         products = products.filter(category=category)
#     return render(request, 'shop/category/product/list.html', {
#         'category': category,
#         'categories': categories,
#         'products': products
#     })

# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm
    return render(request, 'shop/category/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

# class ProductCatCityList(ProductCityList):
#     template_name = 'shop/category/product/list.html'
#     context_object_name = 'category'



# Должны получать товары по городу и категории
# class CityListView(ListView):
#     template_name = 'shop/category/city.html'
#     context_object_name = 'products'
#     # model = Product
#
#     def get_queryset(self):
#         city = City.objects.get(city__slug=self.kwargs['slug'])
#         category = Category.objects.get(category_slug=self.kwargs['slug'])
#         products = Product.objects.filter(city=city, category=category)
#         # products = Product.objects.filter(city__slug=self.kwargs['slug'])
#         # Отбираем первые 10 статей
#         paginator = Paginator(products, 1)
#         page = self.request.GET.get('page')
#         try:
#             products = paginator.page(page)
#         except PageNotAnInteger:
# Если страница не является целым числом, поставьте первую страницу.
#             products = paginator.page(1)
#         except EmptyPage:
# Если страница находится за пределами допустимого диапазона (9999) доставьте последнюю страницу результатов
#             products = paginator.page(paginator.num_pages)
#         return products



class A(ListView):
    template_name = 'shop/base.html'
    context_object_name = 'products'
    model = Product
    def get_queryset(self):
        city = City.objects.get(slug=self.kwargs['slug'])
        products = Product.objects.filter(city=city)
        return products

    def productList(self, category_slug=None):
        category = None
        categories = Category.objects.all()
        products = Product.objects.all()
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        return render('shop/category/product/list.html', {
            'category': category,
            'categories': categories,
            'products': products
        })

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <!-- Styles -->
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
  <section id="header">
    <div class="top container">
      svadba.kz
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Ваша корзина:
                    <a href="{% url "cart:CartDetail" %}">
                        {{ total_items }} тов. {{ cart.get_total_price }} руб.
                    </a>
                {% else %}
                    Корзина пустая
                {% endif %}
            {% endwith %}
        </div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
{#  <div class="row">#}
{#        <div class="col-lg-12" align="center">#}
{#            <ul class="pagination">#}
{#                {% if post.has_previous %}#}
{#                    <li class="arrow"><a href="/blog/city/{{ city.slug }}?page={{ pag }}{{ post.previous_page_number }}">&laquo;</a></li>#}
{#                {% else %}#}
{#                    <li class="disabled"><a href="">&laquo;</a></li>#}
{#                {% endif %}#}
{#                {% for pag in post.paginator.page_range %}#}
{#                    {% if pag == post.number %}#}
{#                        <li class="active"><a href="/blog/city/{{ city.slug }}?page={{ pag }}">{{ pag }}</a></li>#}
{#                    {% else %}#}
{#                        <li><a href="/blog/city/{{ city.slug }}?page={{ pag }}">{{ pag }}</a></li>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{#                {% if post.has_next %}#}
{#                    <li class="arrow"><a href="/blog/city/{{ city.slug }}?page={{ pag }}{{ post.next_page_number }}">&raquo;</a></li>#}
{#                {% else %}#}
{#                    <li class="disabled"><a href="">&raquo;</a></li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#      {% block content1 %}{% endblock %}#}
    {% block content %}{% endblock %}
  </section>
</body>
</html>